### ISSUE TITLE
RPC: getrawtransaction should show more info

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/ocean#117]
For each transaction output the additional fields will need to be added :

- [x] If asset is policy asset, add an additional field with the asset label

- [x] If the scriptPubkey is of type `lockedmultisig`, try parsing a Request/Bid and add Request/Bid information (similar to getrequests/getreqeustbids rpc)

- [x] extend qa tests where policy assets are used to check that getrawtransaction works as expected

- [x] issuance asset changes

For whitelisting the type is already set to `registeraddress` and data is encrypted. Would we want to show anything else @lawlawlaw ?

@tomt1664 do we want to show anything else for freeze/burn either than the asset label?

**Comment by nkostoulas** [comment]
It might also be good to rename the free coin from CBT to something else as it now has a different utility than that of a pegged asset.

**Comment by lawlawlaw** [comment]
"For whitelisting the type is already set to registeraddress and data is
encrypted. Would we want to show anything else @lawlawlaw
<https://github.com/lawlawlaw> ?" - no, that is all.

**Comment by nkostoulas** [comment]
@AstryX to make things a bit clearer could you also make the following changes:

- Add a new asset called issuanceAsset
- add a new asset issuance_asset in consensus and use that for issuanceAsset instead of pegged_asset
- add a new destination called issuanceCoinsDestination and use that for issuanceAsset instead of initialfreecoinsDestination (this will require changes in the unit-tests as well) in chainparams.cpp
- add a new label called ISSUANCE
- add issuanceAsset to IsPolicy()
- leave the previous policyAsset as is for now, as it will require a few changes, but remove it from IsPolicy()
- Run qa tests (qa/pull-tester/rpc-tests.py) and make any fixes required

Upon release you will need to coordinate with @stakauskas to replace initialfreecoinsdestination with issuancecoinsdestination in deployment configuration.

**Comment by nkostoulas** [comment]
This will break config in a few repos but it is best done now as pegged_asset should be used for CBT and not for any policy assets.
