### ISSUE TITLE
Deprecated code whitelist.cpp

### ISSUE THREAD

**Issue by AstryX** [commerceblock/ocean#126]
In the latest version of ocean _tweakedPubKeyMap is used when it is no longer needed. It should be removed. An example can be found in whitelist.cpp line 154.

**Comment by nkostoulas** [comment]
An example of what exactly? It seems to be used in the LookupTweakedPubKey method.

**Comment by AstryX** [comment]
It is a reminder for @lawlawlaw. My apologies for the inaccurate line, local changes have shifted it. It is in whitelist.cpp 114.

**Comment by AstryX** [comment]
Closing this issue as the tweakedPubKeyMap was in fact necessary for registeraddress transaction validation. It was further expanded and adapted. to support verification of Multisig transactions.
