### ISSUE TITLE
policy: Onboarding transactions with errors get partially parsed

### ISSUE THREAD

**Issue by AstryX** [commerceblock/ocean#155]
A discussion was held with fellow developers today whether onboarding transactions that encounter errors should be fully scrapped and not partially parsed instead. At the moment if there are 50 p2pkh addresses to be whitelisted and it fails on the 26th, the first 25 get added to the whitelist and the function is returned as successful as long as it at least adds one address. This behaviour may need to be changed.

**Comment by lawlawlaw** [comment]
Fixed in pull request #248.
