### ISSUE TITLE
Last asset redemption: Conmandatory coinbase maturity confirmation conflict

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/ocean#175]
Conmandatory coinbase (fee) maturity is 100 blocks but inflation is 60 blocks.

When redeeming the last bar, this means the consolidation of DGLD is made slightly tricky because of the timing differences - e.g. fee address accrues inflation before matured and upon sending the final inflation amount it creates another fee which is subject to inflation prior to maturiy

**Comment by nkostoulas** [comment]
resolved
