### ISSUE TITLE
rpc: modify getrequests with an auction only flag 

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/ocean#176]
Currently `getrequests` shows all requests and `getrequests <hash>` returns only the active request per client hash.

Might be useful to have an auction only flag, which returns active requests only for all clients.

**Comment by tomossomot** [comment]
What do you mean by auction only? Requests that are available for bids?

**Comment by nkostoulas** [comment]
Yep where "startBlockheight" has not been reached yet, which means there is a live auction.
