### ISSUE TITLE
wallet: sendtoaddress handling of micro transactions

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/ocean#180]
There reaches a point where the number of micro transactions from inflation/fees is too large to send via ocean RPC.

As per attached, scenario is sending inflation (from inflation address) to another single address, 1-3 DGLD is ok to send but 4+ errors due to transaction too large. This means the consolidation of inflation & fees (simply sending to one address) becomes quite a manually intensive task.

<img width="561" alt="Screenshot 2019-08-01 at 11 17 05" src="https://user-images.githubusercontent.com/31970407/62285996-b514d180-b44e-11e9-94ce-c308cf2a4b89.png">

**Comment by nkostoulas** [comment]
Will be extending the wallet rpcs to create multiple transactions if all can't fit into one.

**Comment by nkostoulas** [comment]
Split transaction logic moved to sendanytoaddress.
