### ISSUE TITLE
wallet: node stuck with AddToWallet spam

### ISSUE THREAD

**Issue by haael** [commerceblock/ocean#184]
After the restart a node takes at least 30 minutes to sync, throwing lots of "AddToWallet" messages.

To reproduce: stop the node, start the node.
Expected behaviour: The node should sync in reasonable time.
Actual behaviour: The node is spending at least 30 minutes printing "AddToWallet" messages.
Version: commerceblock/ocean:1466df239

**Comment by lawlawlaw** [comment]
This was caused by the federation, and was fixed with "federation" repo pull request #30 .
