### ISSUE TITLE
Reissuance Asset Amount & Whitelist Amount

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/ocean#185]
Can this be changed from 10,000 to 1?

Reason is that the additional 4 zeros are extra data that serve no purpose and over time this will accumulate significantly.

For example... 1,000 bars = 72,000 inflation tx's per month / 864,000 per year. So it's a lot of extra data that can be dropped?

**Comment by nkostoulas** [comment]
Probably best this goes to mapping repo. Is the problem the number of outputs or the output amount?

**Comment by cryptopoly** [comment]
Can be closed - variable does not take up extra space :D
