### ISSUE TITLE
wallet: sendtoaddress no fees from coinbase

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/ocean#188]
Ability to disable paying a fee only from conmandatorycoinbase for final bar redemption

**Comment by nkostoulas** [comment]
I guess if we use a multisig for conmandatorycoinbase you will not be able to use sendtoaddress anyway, so maybe this is no longer a priority.

**Comment by nkostoulas** [comment]
Will be implementing a new method to create raw send any so I will work on this too. Might be good to also disable fees on policy assets.
