### ISSUE TITLE
policy: kycfile onboarding issues

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/ocean#217]
When reading the kycfile, if `parsePubkeyPair` or `parseMultisig` fails, reading succeeds without any error. This was observed by having the `contractintx` flag disabled and thus onboarding expected a tweaked address.

Then `onboarduser` succeeds at creating an onboarding transaction with an empty onboarding script, which means that no address is whitelisted.

I am not sure what `_decryptedStream` is doing in kycfile.cpp.

Also `_kycPubKey` seems to never be set in onboardingscript.cpp and when added in `FinalizeUnencrypted` it has no effect.

**Comment by lawlawlaw** [comment]
_kycPubKey is only needed by onboardingscript.cpp for encrypted whitelist.
_decryptedStream is a decrypted stream of text used for writing a plaintext kycfile and is used by the readkycfile rpc.
This issue is fixed in pull request #221.

**Comment by lawlawlaw** [comment]
This issue is fixed in pull request #221.
