### ISSUE TITLE
policy: testmempoolaccept does not check policy rules

### ISSUE THREAD

**Issue by tomossomot** [commerceblock/ocean#223]
`testmempoolaccept` RPC docs state : "This checks if the transaction violates the consensus or policy rules."

But does not check for whitelist/blacklist constraints on the signing keys.

**Comment by tomossomot** [comment]
The policy checks are written in rpc ``testmempoolaccept`` but were disabled by a variable ``test_accept`` which forces automatic acceptance of policy transactions. [This](https://github.com/commerceblock/ocean/compare/master...commerceblock:testmempoolaccept) branch removes the check and so restores full functionality and all tests pass. 

``test_accept`` is not used by any other code.

I assume this is here for testing. Should it be removed, disabled or kept as it is with ``testmempoolaccept`` not checking policy rules.

Or, since all the code is in place, it could be added as an argument to the RPC?

**Comment by nkostoulas** [comment]
It is used further down:
```
    if (test_accept)
      return true;
```
`test_accept` is used to limit how many of the checks in AcceptToMemoryPoolWorker() are required to pass for the rpc `testmempooltoaccept` to succeed. Why remove it or add to the RPC? We can move it further to allow more tests.

Your branch is empty. What are you trying to do?

**Comment by tomossomot** [comment]
I closed issue and removed branch as i had figured it out, sorry.
