### ISSUE TITLE
Node Speed/Performance

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/ocean#247]
Node has become slugish for some reason.

Can take up to 30 seconds to GetBlockchainInfo or to close the node down.

Oceand CPU usage often at 100% (could be parallelised as only single core?)

Slow node general
https://www.dropbox.com/s/es5cjfm5160rdj1/DGLD%20Node%20Slow.mov?dl=0

Slow node sync
https://www.dropbox.com/s/1kiiutksjz10j2q/DGLDCHainSync.mov?dl=0

**Comment by nkostoulas** [comment]
That is because it is syncing the headers. Will be fixed in #246
