### ISSUE TITLE
rpc: get base58prefixes

### ISSUE THREAD

**Issue by tomossomot** [commerceblock/ocean#258]
Rpc getting PUBKEY_ADDRESS base58 prefix. 

Why: Coordinator currently requires ``-nodeaddrprefix`` argument, would be better to have this set behind the scenes. User should not have to know about address prefixes. May be useful for other services interacting with client chains also.

Any other chain params that would be useful to include?

**Comment by nkostoulas** [comment]
All PUBKEY_ADDRESS, BLINDED_ADDRESS, SECRET_KEY, SCRIPT_ADDRESS would be useful. Maybe it is best to append this to an already existing rpc like `getblockchaininfo` or any other? You could have a quick look in bitcoin too maybe they have already implemented something similar, though I couldn't find anything.

**Comment by nkostoulas** [comment]
Would be good to add to https://github.com/commerceblock/rust-ocean-rpc too after. The coordinator would use that.

**Comment by tomossomot** [comment]
If were going to add to an exisiting rpc then ``getblockchaininfo`` is best. 

Another thing that would be useful for coordinator is block time. This would require taking ``median time`` field from ``getblockheader`` from several blocks and returning the mode average. Not sure if thats a bit risky though

**Comment by tomossomot** [comment]
Unless block time is specified somewhere that i cant find?

**Comment by nkostoulas** [comment]
Block time is not node consensus, so nodes can't really tell. Federation decides how often to produce blocks. I don't think we are moving from 1min blocks any time soon, so you can leave that.

**Comment by tomossomot** [comment]
just found ``getsidechaininfo``, will add to that instead
