### ISSUE TITLE
oceand runs without complaining with invalid options

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/ocean#261]
If oceand is started with an invalid e.g. misspelled option, it will carry on without complaining. This can result in errors creeping into config files due to spelling mistakes etc.

I propose to upgrade the current option parsing system to stop with an appropriate error message if any option in the option map is not present in a predetermined list of valid options.

**Comment by nkostoulas** [comment]
Might be worth checking upstream elements/bitcoin. They have changed the whole argument system.

**Comment by tomossomot** [comment]
Bitcoin/Elements now store all possible arguments in an Arg struct, along with arguments provided by the user so checking for correct input is easy. It is a big change though and would take some time, but may be worth doing https://github.com/bitcoin/bitcoin/pull/9243.

Other hacky options are:
- generate the helpMessage strings, parse into a list of all arguments and check inputs against it
- store a seperate list of argument strings to check against

**Comment by nkostoulas** [comment]
Yeah big change and a bit fiddly. I've added this to the list of upstream changes we should consider (https://github.com/commerceblock/ocean/milestone/4) already. Not sure if it's worth doing at the moment but if we do this we do it proper.

**Comment by tomossomot** [comment]
Yup, I'll start looking into it now and get an idea of how big the job is
