### ISSUE TITLE
Re-branding

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/ocean#44]
Re-brand: Elements -> Ocean

script, daemon and client names. 
file names (config etc)
std output.

**Comment by lodenos** [comment]
It's ready
https://github.com/commerceblock/ocean/tree/feature/rename_brand

**Comment by lodenos** [comment]
But I go make a new branch special develop for the development of Ocean

**Comment by nkostoulas** [comment]
All tests running ok?

**Comment by nkostoulas** [comment]
You also need to do the same for:
https://github.com/commerceblock/federation
but very few changes.

Also https://github.com/commerceblock/ocean-demo if anyone is using it.

And https://github.com/commerceblock/infrastructure it is used a lot, maybe talk to @stakauskas

**Comment by nkostoulas** [comment]
QT test I ignore. It never runs on my computer and we don't use anyway.

The other I'm not sure. What's in src/test-suite.log ?

**Comment by lodenos** [comment]
Ok this the contant of src/test-suite.log

**Comment by lodenos** [comment]
@nkostoulas Nice, Good found it, Thanks

**Comment by nkostoulas** [comment]
Tests and federation rebranded. 

Only https://github.com/commerceblock/infrastructure missing, which is going to affect the whole deployment @lodenos @stakauskas .
