### ISSUE TITLE
Guardnode: request permissions

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/ocean#52]
Requests in the guardnode system must be permissioned (i.e. only authorised partners - client chains - can issue requests). Permission tokens are required to issue requests. 
This works as follows:
Permission tokens (permissionAsset) are (optionally) issued to a given address in the genesis block, e.g.:
permissionassetcoins=5000000
permissionassetdestination=g4e638a7cc43....     (the scriptPubKey of the permissionasset output). 

This scriptPubKey (multisig or P2PKH) is owned by the 'controller'. The controller sends a quantity of the permissionAsset to a client chain so they can submit requests.

**Comment by nkostoulas** [comment]
Also add asset label and modify createrawrequest unit tests to use this new asset.

**Comment by nkostoulas** [comment]
@tomt1664  Do we need a mempool rule for this or is it just a way to distinguish policy requests?

**Comment by nkostoulas** [comment]
I guess such a transaction will only go through anyway if you have a policy asset only.
