### ISSUE TITLE
Policy lists via UTXO: lists updated before block confirmation.

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/ocean#59]
This currently applies to the utxolists branch.

In validation.cpp, in ConnectBlock. The policy lists are updated from the transactions in the block before the block is fully validated; ConnectBlock could later return "false" with CValidationState other than "MODE_VALID".

**Comment by nkostoulas** [comment]
Is this still a problem?

**Comment by lawlawlaw** [comment]
Potentially, yes. Ideally, the policy lists etc. should be updated just before the "return true". However, this could affect transactions within the same block that depend on policy.

**Comment by nkostoulas** [comment]
Ok this sounds serious. Affect how do you mean?

**Comment by lawlawlaw** [comment]
For example, an address is added to the freeze list in a policy transaction. In a later transaction, in the same block, the asset from the frozen address is spent. So in this case the earlier transaction invalidates the later transaction.

**Comment by lawlawlaw** [comment]
Unless we want policy list changes only to take effect in the next block.

**Comment by nkostoulas** [comment]
I think this part is fine since policy lists are used for mempool rejection. Still we shouldn't be updating them until the block is fully validated.

**Comment by lawlawlaw** [comment]
I'll push a fix for this in a moment. 
Another possible issue is if e.g. DisconnectBlock is called, the policy lists wont be updated.
This also affects AssetMap and FreezeHistory.

**Comment by nkostoulas** [comment]
partly resolved. relevant issue open #128
