### ISSUE TITLE
Genesis issued coins not being added to wallet

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/ocean#70]
When additional assets are issued in the genesis block (policy assets), not all of them are being picked up by wallets. It seems only the last 100 outputs are being listed. 

e.g. with freezelist and burnlist assets issued (along with the freecoins) there are 300 outputs in the genesis UTXO (as confirmed with `gettxoutsetinfo`). These assets are issued to P2PKH pubkeyScripts. 

If I then import the corresponding addresses to an Ocean wallet (with `importaddress`) only the last 100 outputs are picked up by the wallet (confirmed with `listunspent`) - i.e. only the burnlist assets in the example. 

All outputs are spendable with manually constructed transactions, it's just the wallet scanning.

**Comment by lawlawlaw** [comment]
I moved the free coin issuance transaction to the end genesis block (after the policy asset issuances) so these outputs are imported into the wallet (whitelisttransactions branch).

**Comment by nkostoulas** [comment]
All issuance transactions use the same dummy prevout, appearing as conflicting transactions in the wallet.
